definitions:
  http.JSONError:
    properties:
      error:
        type: string
    type: object
  http.SignInRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  http.SignInResponse:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  http.SignUpRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  http.SignUpResponse:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  http.createRequest:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  http.createResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  http.listResponse:
    properties:
      workspaces:
        items:
          $ref: '#/definitions/http.workspaceResponse'
        type: array
    type: object
  http.workspaceResponse:
    properties:
      boards:
        items:
          $ref: '#/definitions/models.Board'
        type: array
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  internal_users_delivery_http.getResponse:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  internal_users_delivery_http.partialUpdateRequest:
    properties:
      email:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
  internal_workspaces_delivery_http.getResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
  internal_workspaces_delivery_http.partialUpdateRequest:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  models.Board:
    properties:
      background:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
      workspace_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /auth/logout:
    delete:
      description: Logs out and deletes the authentication cookie.
      produces:
      - application/json
      responses:
        "204":
          description: Successfully logged out.
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      security:
      - cookieAuth: []
      summary: Logs out and deletes the authentication cookie.
      tags:
      - auth
  /auth/signin:
    post:
      consumes:
      - application/json
      description: Logs in and returns the authentication cookie
      parameters:
      - description: Successfully authenticated.
        in: body
        name: signInParams
        required: true
        schema:
          $ref: '#/definitions/http.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: successfully auth
          schema:
            $ref: '#/definitions/http.SignInResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Logs in and returns the authentication cookie
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Creates new user and returns authentication cookie.
      parameters:
      - description: Sign up params.
        in: body
        name: signUpParams
        required: true
        schema:
          $ref: '#/definitions/http.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created user.
          schema:
            $ref: '#/definitions/http.SignUpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      summary: Creates new user and returns authentication cookie.
      tags:
      - auth
  /users/{id}:
    get:
      description: Returns user with specified id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User data
          schema:
            $ref: '#/definitions/internal_users_delivery_http.getResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      security:
      - cookieAuth: []
      summary: Returns user with specified id
      tags:
      - users
    patch:
      consumes:
      - application/json
      description: Partial update of user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User data to update
        in: body
        name: UserUpdateData
        required: true
        schema:
          $ref: '#/definitions/internal_users_delivery_http.partialUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Updated user data
          schema:
            $ref: '#/definitions/internal_users_delivery_http.getResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/http.JSONError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      security:
      - cookieAuth: []
      summary: Partial update of user
      tags:
      - users
  /workspaces:
    get:
      description: Returns all workspaces with boards of current user
      produces:
      - application/json
      responses:
        "200":
          description: Workspaces data
          schema:
            $ref: '#/definitions/http.listResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      security:
      - cookieAuth: []
      summary: Returns all workspaces with boards of current user
      tags:
      - workspaces
    post:
      consumes:
      - application/json
      description: Create a new workspace
      parameters:
      - description: Workspace create data
        in: body
        name: WorkspaceCreateData
        required: true
        schema:
          $ref: '#/definitions/http.createRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Created workspace data.
          schema:
            $ref: '#/definitions/http.createResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      security:
      - cookieAuth: []
      summary: Create a new workspace
      tags:
      - workspaces
  /workspaces/{id}:
    delete:
      description: Delete workspace by id
      parameters:
      - description: Workspace ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: Workspace deleted successfully
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      security:
      - cookieAuth: []
      summary: Delete workspace by id
      tags:
      - workspaces
    get:
      description: Returns workspace by id
      parameters:
      - description: Workspace ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Workspace data
          schema:
            $ref: '#/definitions/internal_workspaces_delivery_http.getResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      security:
      - cookieAuth: []
      summary: Returns workspace by id
      tags:
      - workspaces
    patch:
      consumes:
      - application/json
      description: Partial update of workspace
      parameters:
      - description: Workspace ID
        in: path
        name: id
        required: true
        type: integer
      - description: Workspace data to update
        in: body
        name: WorkspaceUpdateData
        required: true
        schema:
          $ref: '#/definitions/internal_workspaces_delivery_http.partialUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Updated workspace data.
          schema:
            $ref: '#/definitions/internal_workspaces_delivery_http.getResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.JSONError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.JSONError'
        "405":
          description: Method Not Allowed
        "500":
          description: Internal Server Error
      security:
      - cookieAuth: []
      summary: Partial update of workspace
      tags:
      - workspaces
swagger: "2.0"
